dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/postcss.config.js
dluhc-component-library/src/components/siteSelectionForm.tsx
dluhc-component-library/src/index.css
dluhc-component-library/src/main.tsx
dluhc-component-library/tailwind.config.js

Adds tailwind to the component library.
Tailwind will allow us to rapidly prototype our POCs and reduce time spent on css.
I have added a quick example of using tailwind to the temporary site selection form component

Add tailwind

---

dluhc-component-library/index.html
dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/src/components/maps/baseMap.tsx
dluhc-component-library/src/components/maps/mapContainer.tsx
dluhc-component-library/src/components/siteSelectionForm.tsx
dluhc-component-library/src/contexts/mapContext.tsx
dluhc-component-library/src/main.tsx

* Adds a basic map component and context container that we can build upon.
* Renders an example map on the index page

DLUHC-204 add map component

---

.github/workflows/storybook.yml
dluhc-component-library/package.json

Adds a github action to deploy storybook onto github pages

Add storybook gh workflow

---

dluhc-component-library/src/components/maps/baseMap.tsx

Built out the basics of drawing on the map.
- To be used in the process of site selection

added basic drawing capabilities

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/MultiSelect.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts

Continues adding more functionality to the Site Selection Form. Form data across questions is now stored and is in the format of common form data.
My plan was to use Formik for this however it seemed to be having an typescript issue with preact. For now i have written a custom solution but this may need to be revisted for validation and errors

DLUHC-175 Add form state

---

dluhc-component-library/src/api/api.ts
dluhc-component-library/src/api/types.ts
dluhc-component-library/src/components/datasets/DatasetList.tsx
dluhc-component-library/src/components/datasets/DatasetSelect.tsx
dluhc-component-library/src/components/datasets/types.ts

- Adds an API call to fetch the list of possible datasets from PDP
- Refactor existing fetch datasets call to be an arrow function

DLUHC-204 add api call to get dataset list

---

dluhc-component-library/src/components/maps/baseMap.tsx
dluhc-component-library/src/components/maps/drawingLayer.tsx
dluhc-component-library/src/components/maps/mapContainer.tsx
dluhc-component-library/src/components/maps/mapLayer.tsx
dluhc-component-library/src/main.tsx
dluhc-component-library/src/stories/DrawingLayer.stories.tsx
dluhc-component-library/src/stories/Map.stories.tsx
dluhc-component-library/src/stories/MapLayer.stories.tsx

Taken drawing functionality and built it into own component. Added Zindex prop for organizing layers of maps.

Separated drawing into own component

---

dluhc-component-library/src/components/timetablePage/AccordionDropdown.tsx

changed arrow on 'more information' so that when it is clicked it shows the extra info

change arrow to drop down more info

---

dluhc-component-library/plan-making/assets/timetableHeader.csv
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx
dluhc-component-library/src/components/timetablePage/types.ts
dluhc-component-library/src/main.tsx
dluhc-component-library/src/stories/TimetablePage.stories.tsx

Reverts digital-land/plan-making#29

Revert "DLUHC-200-Add timetable headers from csv"

---

dluhc-component-library/plan-making/assets/timetableHeader.csv
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx
dluhc-component-library/src/components/timetablePage/types.ts
dluhc-component-library/src/main.tsx
dluhc-component-library/src/stories/TimetablePage.stories.tsx

fix to https://github.com/digital-land/plan-making/pull/29 where the story filepath name was inconsistent with what was being used, now fixed

fix - DLUHC-200-add timetable headers from csv

---

dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/stories/DrawingLayer.stories.tsx
dluhc-component-library/src/stories/Map.stories.tsx

Created a wrapper component which takes in the various props required for most child elements

Wrapper Map Component

---

dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/main.tsx

Fixed the casing for `MapContainer` in `MapComponent`

DLUHC-264 fix the casing for MapContainer in MapComponent

---

dluhc-component-library/src/components/siteSelectionForm/utils.ts

Adds the types of radio button output to the radio options helper util.

Add radio option type to convert util

---

scripts/README.md
scripts/setupminio.sh
scripts/startminio.sh

Adds scripts to do first time setup for MinIO and a script to start the server.

DLUHC-177 Add  MinIO scripts

---

dluhc-component-library/src/api/aws/api.ts

Fixes typo in access key, should allow submission to MinIO now

DLUHC-177 bugfix: access key

---

dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/src/api/aws/api.ts
dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/FormPage.tsx

This PR adds submit function back in, and migrates to AWS SDK v3 to see if that fixes the GH pages bug.

DLUHC-177 Add submit function using AWS SDK v3

---

dluhc-component-library/src/components/timetablePage/Timetable.tsx
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx
dluhc-component-library/src/components/timetablePage/columnDefinitions.tsx

when the dates cam from the JSON they where in the ISO format, this PR formats them from the ISO to a readable format.
startDate, endDate and published date have been changed

201 timetable date formatter

---

dluhc-component-library/src/stories/MapLayer.stories.tsx

changed mapLayer story

---

dluhc-component-library/src/stories/MapLayer.stories.tsx

fixed naming in MapLayer

---

dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/components/maps/components/MapLayer.tsx
dluhc-component-library/src/stories/MapLayer.stories.tsx

auto focus on the boundary if there is one 
with 
without

auto zoom to boundary area

---

dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

Added json shcema to replicate the figma made here in round 2 of design: https://www.figma.com/file/cSgUTztlijSmccSSt7uCMv/Site-Identification?type=design&node-id=1148-3085&mode=design
(i have a gif for demonstration, cant put it here for some reason)

227 json schema site identification

---

dluhc-component-library/README.md
dluhc-component-library/vite.config.ts
prototype-kit/app/views/index.html

Add component lib to prototype kit
