digital-land/plan-making

dluhc-component-library/.storybook/main.ts
dluhc-component-library/.storybook/preview.ts
dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/src/components/timetablePage/Timetable.tsx
dluhc-component-library/src/stories/.eslintrc.json
dluhc-component-library/src/stories/Map.stories.tsx
dluhc-component-library/src/stories/TimetablePage.stories.tsx

This PR adds storybook as dev dependency. Story book creates a website which allows us to display our library components in an organised manner as well as adding documentation around them without adding more code to the end JS artefact. 
For each component we want to show, we add a new story file in the stories folder detailing what props we want to expose and what we want to call the component. It then adds a new item to the navigation bar and renders our component. As shown below with the timetable page.
This will give programmers an organised platform to develop against rather than fighting over the index.html file.
There is probably more discussion to be had around how we want to layout our components, maybe as components and pages. Another thing to discuss is do we want to try to …

Add story book

---

dluhc-component-library/src/components/timetablePage/Timetable.tsx
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx

adds csv to immitate gov website for the text info in the timetable page

add top half of time table css

---

dluhc-component-library/src/components/timetablePage/ProgressTile.tsx
dluhc-component-library/src/components/timetablePage/Timetable.tsx
dluhc-component-library/src/components/timetablePage/columnDefinitions.tsx
dluhc-component-library/src/components/timetablePage/types.ts

- Pulls out the column definitions into their own file
- Pulls the types out into a type file
- Converts the progress camel case value into human readable strings

Refactor progress tile and types

---

dluhc-component-library/package-lock.json
dluhc-component-library/package.json

Bad rebase removed  `csvtojson` dependency - this PR adds it back in.

Bugfix: add csvtojson dependency

---

dluhc-component-library/src/components/datasets/DatasetList.tsx
dluhc-component-library/src/components/datasets/DatasetSelect.tsx
dluhc-component-library/src/components/datasets/types.ts

- Adds a component that can take a list of datasets and render them as a list. This will be used to select which datasets a LPA is interested in validating.
- The format of datasets matches the response from PDP: https://www.planning.data.gov.uk/dataset.json more fields such as description can be added later if needed.
In following PRs will add:
- Colour key for each layer
- Render layers based on selection

DLUHC-204 add list component for map layers

---

dluhc-component-library/src/api/api.ts
dluhc-component-library/src/components/maps/baseMap.tsx

Data from drawn polygon now makes an API request to PDP to see if any notable sights fall within the bounds of the drawn site.

drawn polygon coordinates are used in API request

---

dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/src/api/api.ts
dluhc-component-library/src/components/datasets/DatasetList.tsx
dluhc-component-library/src/components/maps/DatasetLayer.tsx
dluhc-component-library/src/components/maps/mapContainer.tsx
dluhc-component-library/src/stories/DatasetSelection.stories.tsx

This PR creates a storybook component that take selected datasets and renders the response GeoJSON on a map component:
- Added React Query library
- Added API call to fetch an individual dataset
- Added loading state to `DatasetList` component
- Added `DatasetLayer` to fetch dataset GeoJSON and render it in a `MapLayer` component
- Added a storybook component for dataset selection
To be done in a future PR:
- Take colour from dataset object (if it exists) and use that instead of default blue colour.
- Find a more efficient way to get map bounds

DLUHC-204 add story for loading planning data platform datasets on a map

---

dluhc-component-library/src/api/types.ts
dluhc-component-library/src/components/datasets/DatasetSelect.tsx
dluhc-component-library/src/components/maps/DatasetLayer.tsx

Each dataset object has an optional `paint-options` field. If this field is present calculates the stroke and fill for the polygon to be rendered. If it is not present will default to dark blue (matching https://www.planning.data.gov.uk/map/).
The below map shows:
- Article 4 direction area (default dark blue)
- Historic parks and gardens (green)
- Scheduled monument (light blue)

DLUHC-204 apply dataset colours to layers on map

---

dluhc-component-library/package-lock.json
dluhc-component-library/package.json
dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

This PR adds  basic validation for the form using the `yup` package. Currently only validates `string` text input boxes, and only displays one error.

DLUHC-175 Add form validation

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/Input.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

This PR fixes the number parsing where previously numbers were being stored in the state as strings, and validates that a number has been put in if it is a required field

DLUCH-175 validate numbers

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/Input.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

This is a step towards handling conditional properties (questions).
The code recursively looks over the entire schema and flattens all the nested properties into one property object for the form to iterate over.
The potential problem with this is when it comes to validating the form values back against the schema since they will have lost the indentation. This can be fixed in the future as that is currently not a requirement.

DLUHC-175 Handle object type

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

Adds the ability for our site identification form to check the dependencies and add additional properties if there is a value present (not specific values yet).
_This is hard to show in screenshots so i recommend testing out the branch_
If you skip the "Parent question", you should go straight to the "Unrelated question".
If you answer the "Parent question", an "Additional question" should be inserted before the "Unrelated question" and be required.

Add form dependency logic

---

dluhc-component-library/src/components/maps/MapComponent.tsx

Previously if one property on the mapComponent was changed then all of the default properties were lost. Now individual properties are customizable while retaining defaults for those not customized

Made components more customizable

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/BooleanInput.tsx
dluhc-component-library/src/components/siteSelectionForm/components/Checkbox.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

Adds a boolean input type and validates that it has been checked. 
Uses a simple checkbox for the boolean input and as such, after it's been checked it's either `true` or `false` in the state so will pass validation if the box isn't checked. 
Have left the validation as-is - could force it to want a `true` or remove from state if false but this is the easiest way to do an example

DLUHC-175 Add boolean validation

---

dluhc-component-library/src/stories/MapLayer.stories.tsx

Fix the casing for the `MapContainer` import in the `MapLayer` story.

DLUHC-264 fix import casing

---

dluhc-component-library/src/components/maps/DrawingLayer.tsx
dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/components/maps/types.ts
dluhc-component-library/src/stories/DrawingLayer.stories.tsx

Adds the drawable boundary as an input to the `MapComponent` effectively turning the map into a controlled input for boundary drawing. The data format is a `number[][][]` representation of the polygon. Currently only supports drawing 1 boundary, if another boundary is drawn the old one will get deleted.
- Added value as input to `MapComponent` and `Drawinglayer`
- Updated output return type to be `number[][][]`
- Removed the `div` ref from drawing layer. It's wasn't needed since the drawing layer is always a child of the map container which has a map defined.
- Added types for `Coordinate`, `LinearRing` and `Polygon`
Boundary editing will be added in a future PR.

DLUHC-264 add boundary value input

---

dluhc-component-library/src/components/accordianDropdown/AccordionDropdown.tsx
dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/FormPage.tsx
dluhc-component-library/src/components/siteSelectionForm/components/MapPage.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/components/timetablePage/Timetable.tsx
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx
dluhc-component-library/src/stories/SiteSelection.stories.tsx

This PR adds a basic map page to the dynamic form.
Currently its using a schema type of "map" which is not valid. This is just temporary until the form supports a uiSchema alongside the jsonSchema.

DLUHC-176 Add map page to dynamic form

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/components/RadioButtons.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/components/siteSelectionForm/utils.ts
dluhc-component-library/src/stories/SiteSelection.stories.tsx

Adds a basic uiSchema so that we handle maps and radio options more inline with jsonSchema + uiSchema.
The Radio component now handles both strings and booleans but still allows the validation system to check its the correct value.
The map page hasnt really been changed, ideally i was hoping to be able to change the the jsonSchema type to be the correct type but this requires the array PR to me merged.

DLUHC-176 Site selection UI schema

---

dluhc-component-library/src/components/siteSelectionForm/components/RadioButtons.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts

The type of the radio button option value was `string | boolean` however this wasnt being aligned with the type that was being given to the radio button component. This type is now dynamic and driven by the type of the radio button component

Fix radio option value type

---

dluhc-component-library/src/components/siteSelectionForm/SiteSelectionForm.tsx
dluhc-component-library/src/stories/SiteSelection.stories.tsx

There was a bug that was deleting the `required` field from a property if it had a child that didnt have any required values. 
The code now always adds the parent required values.

Fix required being deleted from top level form

---

dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/components/maps/components/DrawingLayer.tsx
dluhc-component-library/src/components/maps/utils.ts
dluhc-component-library/src/stories/DrawingLayer.stories.tsx

This add a new interaction to the drawing layer which allows a drawn boundary to be edited. These edits are: moving the vertices (corners) of the polygon or adding more vertices. Every time an edit finishes, the updated coordinates are emitted as an output of the `DrawingLayer` and `MapComponent`, in the same way the initial boundary is emitted with the `onChange` callback.
- Added interaction to drawing layer for modifying drawn boundary.
- Updated props to allow vertex shape, size and radius to be configurable.
- Updated drawing default props to use red colours to make it easier to see on the map.
- Also added props to configure drawing pointer style.

DLUHC-264 editable map boundary

---

dluhc-component-library/src/api/planningData/api.ts
dluhc-component-library/src/components/maps/components/DatasetLayer.tsx
dluhc-component-library/src/components/siteSelectionForm/components/MapPage.tsx

Adds the base risk functionality to the boundary selection page.
Whenever a new boundary is drawn, it sends a requests to PDP to see what areas it overlaps with. It then compares that to a list of datasets we actually care about and flags any that match.
In the future we would hopefully be able ask PDP to only check datasets we care about rather than checking them all and filtering down after which is much slower.
I need to have a think about how we want to store the constants used in this as some of them will come from the jsonSchema / uiSchema but they need to match with PDP.
**Loading**
**Risks**
**Notes**
This PR is pointed towards the `dluhc-176-boundary-risks` branch instead of main since the map component is being used in user research sessions so we dont want half finished …

DLUHC-176 Add risk request and display to boundary selection page

---

dluhc-component-library/src/components/maps/MapComponent.tsx
dluhc-component-library/src/components/maps/components/DatasetControl.tsx
dluhc-component-library/src/components/siteSelectionForm/components/MapPage.tsx

Adds a new prop to the map component that allows the user to filter the list of shown datasets.

Add filter for dataset list

---

dluhc-component-library/src/components/loadingSpinner/LoadingSpinner.css
dluhc-component-library/src/components/loadingSpinner/LoadingSpinner.tsx
dluhc-component-library/src/components/siteSelectionForm/components/MapPage.tsx

Adds a basic loading spinner component and adds it to the map page instead of the loading text

DLUHC-176 Add basic loading spinner to map page

---

dluhc-component-library/src/components/formComponents/dateInput/DateInput.tsx
dluhc-component-library/src/components/formComponents/input/Input.tsx
dluhc-component-library/src/components/formComponents/textarea/Textarea.tsx
dluhc-component-library/src/components/timetableForm/TimetableForm.tsx
dluhc-component-library/src/components/timetableForm/components/DescriptionPage.tsx
dluhc-component-library/src/components/timetableForm/components/PublishedDatePage.tsx
dluhc-component-library/src/components/timetableForm/components/TitlePage.tsx

added styling for the timetbale form component.
followed these references:
https://www.figma.com/file/XaBQCco5EI92PaBDXq7Mqq/DLUHC-New-Local-Plans-timetable-dashboard-concepts?type=design&node-id=0-1&mode=design
https://design-system.service.gov.uk/components/

add Dluhc 201 timetable form styling

---

dluhc-component-library/src/components/formComponents/input/Input.tsx
dluhc-component-library/src/components/formComponents/textarea/Textarea.tsx
dluhc-component-library/src/components/policyForm/PolicyForm.tsx
dluhc-component-library/src/components/policyForm/constants.ts
dluhc-component-library/src/components/policyForm/types.ts
dluhc-component-library/src/stories/PolicyForm.stories.tsx

Adds the foundation for the policy form. I haven't been able to get hold of any wireframes yet so this is primarily just a guess by looking at existing policies.
I still need to add a multiselect for the themes the policy links to and potentially a way to link to other policies.

DLUHC-203 Add basic policy form

---

dluhc-component-library/src/components/timetableForm/TimetableForm.tsx
dluhc-component-library/src/components/timetableForm/components/ExportPgae.tsx
dluhc-component-library/src/components/timetableForm/components/StagePage.tsx
dluhc-component-library/src/components/timetableForm/constants.ts
dluhc-component-library/src/components/timetableForm/types.ts
dluhc-component-library/src/components/timetableForm/utils.ts
dluhc-component-library/src/models/timetable/types.ts

Added page to the end of the timetable form to download the timetable data as a JSON file.
- Added new `ExportPage`  which has a button to download the form data as JSON.
- File is called `timetable.json` and goes into the downloads folder.
- Added utility methods to convert form data to JSON data format.

DLUHC-201 add download of timetable json

---

dluhc-component-library/src/components/formComponents/input/Input.tsx
dluhc-component-library/src/components/formComponents/textarea/Textarea.tsx
dluhc-component-library/src/components/policyForm/PolicyForm.tsx
dluhc-component-library/src/components/policyForm/components/MultiItem.tsx
dluhc-component-library/src/components/policyForm/constants.ts
dluhc-component-library/src/components/policyForm/types.ts

Updated the form layout to follow the CMS wireframe format and questions.
This implementation is missing the time period section but that will be done in another PR.
The MultiItem component should also take a component to map over but for a first step it only works with base text inputs.

DLUHC-203 Update policy form to follow wireframe

---

dluhc-component-library/plan-making/assets/newTimetable.json
dluhc-component-library/src/components/timetableForm/TimetableForm.tsx
dluhc-component-library/src/components/timetableForm/components/LandingPage.tsx
dluhc-component-library/src/components/timetableForm/constants.ts
dluhc-component-library/src/components/timetableForm/utils.ts
dluhc-component-library/src/components/timetablePage/TimetablePage.tsx
dluhc-component-library/src/models/timetable/types.ts

Added functionality to timetable landing page to upload an existing timetable into the form.
- Added file type input and styled to look like a button.
- Added utils to convert between JSON representation of a timetable and form representation.
- Changed date type in JSON to be a number so it can be parsed more easily.

DLUHC-201 upload timetable JSON into form

---

dluhc-component-library/plan-making/assets/policy.json
dluhc-component-library/src/components/policyForm/PolicyForm.tsx
dluhc-component-library/src/components/policyPage/PolicyPage.tsx
dluhc-component-library/src/stories/PolicyPage.stories.tsx

Adds the policy form visualization  skeleton
- adds the story
- adds the policy form visualization page
- adds mock json data to be used in next pr
- changes button in form to be onclick (andy)

Add Policy form visualization

---

dluhc-component-library/plan-making/assets/policy.json
dluhc-component-library/src/components/policyForm/PolicyForm.tsx
dluhc-component-library/src/components/policyForm/constants.ts
dluhc-component-library/src/components/policyForm/types.ts
dluhc-component-library/src/components/policyPage/PolicyPage.tsx
dluhc-component-library/src/stories/PolicyPage.stories.tsx

changed the policy form to now use the data given from the json file produced by the policy form.

change Policy form to use json

---

dluhc-component-library/src/components/siteSelectionForm/components/DynamicForm.tsx
dluhc-component-library/src/components/siteSelectionForm/types.ts
dluhc-component-library/src/components/siteSelectionForm/utils.ts

A recent change [(DLUHC-203)](https://github.com/digital-land/plan-making/pull/79/files) broke multiselect in the site identification form. This is because it converted the options from strings to keys and labels.
This PR fixes that by adding a new util that converts an enums to valid options. 
Also fixed a TSlint issue with `validationShape` not being used.
**Notes**
The options of multiselect and radio buttons should be linked up. This is a little hard since radio buttons also allow booleans but it should be investigated in the future.

BugFix - Fix Multiselect options in dynamic form

---

dluhc-component-library/plan-making/assets/policy.json
dluhc-component-library/src/components/policyPage/PolicyPage.tsx

Quick misc PR containing some of the changes done for screenshots in the final reports.
Updated the policy data to follow an existing plymouth policy page
Updated the css to be more uniform and display as bullet points
Updated the themes to display the correct human readable labels rather than keys.

MISC Format policy page lists
